---
  kind: pipeline
  name: testing

  platform:
    os: linux
    arch: amd64

  steps:
  - name: release
    image: node:13
    environment:
      NODE_ENV: gh-pages
    commands:
    - npm install
    - npm run build
